C     ****d* contourfinder/MAXDIM [1.0] *
C   NAME
C     MAXDIM -- the maximum number of dimensions allowed.
C
C   DESCRIPTION
C     This constant defines the maximum dimension of the function that
C     is passed to CONFIND().
C
C   AUTHOR
C     Rahman Amanullah (rahman@physto.se)
C
C   CREATION DATE
C     2000-08-20
C
C     ***


C
C        The maximum number of dimensions allowed.
C
      INTEGER MAXDIM
      PARAMETER ( MAXDIM = 10 )

C     *** End of MAXDIM ***
