C     ****d* snalys/STDOUT [1.0] *
C   NAME
C     STDOUT -- unit id where to send the standard output.
C
C   AUTHOR
C     Rahman Amanullah (rahman@physto.se)
C
C   CREATION DATE
C     2001-03-22
C
C     ***
      INTEGER STDOUT
      PARAMETER ( STDOUT=6 )


C     ****d* snalys/STDERR [1.0] *
C   NAME
C     STDERR -- unit id where to send the standard error.
C
C   AUTHOR
C     Rahman Amanullah (rahman@physto.se)
C
C   CREATION DATE
C     2001-03-22
C
C     ***
      INTEGER STDERR
      PARAMETER ( STDERR=6 )


C
C End of error.inc
C
