C     ****v* snalys/OUTFILE [1.0] *
C   NAME
C     OUTFILE -- name of the output file
C
C   AUTHOR
C     Rahman Amanullah (rahman@physto.se)
C
C   CREATION DATE
C     2001-03-22
C
C   NOTE
C     The values of this should be set once and for all in init.f.
C
C     ***
	CHARACTER*(256) OUTFILE
	COMMON /OUTPUT/OUTFILE



C     ****v* snalys/OFID [1.0] *
C   NAME
C     OFID -- output unit id
C
C   AUTHOR
C     Rahman Amanullah (rahman@physto.se)
C
C   CREATION DATE
C     2001-03-22
C
C   NOTE
C     The values of this should be set once and for all in init.f.
C
C     ***
	INTEGER OFID
	COMMON /OFID/OFID

C
C       End of file.
C
